Update docker-compose-cli.yml

diff --git a/.github/workflows/docker-compose-cli.yml b/.github/workflows/docker-compose-cli.yml
--- a/.github/workflows/docker-compose-cli.yml
+++ b/.github/workflows/docker-compose-cli.yml
@@ -17,6 +17,12 @@ jobs:
     - name: 🛠️ Set up Docker Buildx (for caching & multi-platform builds)
       uses: docker/setup-buildx-action@v3
 
+    - name: Ensure hostsed exists
+      uses: 	@if ! hostsed --help >/dev/null 2>&1; then \
+		            echo "hostsed not found. Installing..."; \
+		          sudo apt update && sudo apt install -y hostsed; \
+            	fi
+             
     - name: 🎯 Cache Docker Layers
       uses: actions/cache@v3
       with:
